routes/web.php
<?php

use Bittacora\Multimedia\Http\Controllers\MultimediaController;
use Illuminate\Support\Facades\Route;

Route::prefix('bpanel')->middleware(['web', 'auth', 'admin-menu'])->name('multimedia.')->group(function(){
    Route::get('/multimedia', [MultimediaController::class, 'index'])->name('index');
    Route::get('/multimedia/create', [MultimediaController::class, 'create'])->name('create');
    Route::get('/multimedia/{multimedia}/show', [MultimediaController::class, 'show'])->name('show');
    Route::get('/multimedia/{multimedia}/edit', [MultimediaController::class, 'edit'])->name('edit');
    Route::post('/multimedia/store', [MultimediaController::class, 'store'])->name('store');
    Route::put('/multimedia/{multimedia}', [MultimediaController::class, 'update'])->name('update');
    Route::delete('/multimedia/{multimedia}', [MultimediaController::class, 'destroy'])->name('destroy');
    Route::get('/multimedia/multiupload', [MultimediaController::class, 'multiUpload'])->name('multiupload');
    Route::post('/multimedia/multiuploadstore', [MultimediaController::class, 'multiUploadStore'])->name('multiuploadstore');
    Route::post('/multimedia/singleuploadstore', [MultimediaController::class, 'singleUploadStore'])->name('singleuploadstore');
    Route::post('/multimedia/bulkdelete', [MultimediaController::class, 'bulkDelete'])->name('bulkdelete');
    Route::post('/multimedia/deletefromupload', [MultimediaController::class, 'deleteFromUpload'])->name('deletefromupload');
});

resources/views/create.blade.php
@extends('bpanel.layouts.bpanel-app')

@section('title', 'Añadir archivo')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('multimedia::form.add') }}</span>
            </h4>
        </div>
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('multimedia.store')}}" enctype="multipart/form-data">
            @csrf

            @livewire('form.input-file', ['name' => 'file', 'labelText' => __('multimedia::form.attach_file'), 'required' => true, 'accept' => $allowedFormats,
            'maxFileCount' => 1, 'allowedFileExtensions' => $allowedExtensions])
            @livewire('form.input-text', ['name' => 'name', 'labelText' => __('multimedia::form.name')])
            @livewire('form.input-text', ['name' => 'keywords', 'labelText' => __('multimedia::form.keywords')])

            @foreach($languages as $language)
                    <div class="card-header bgc-secondary-d1 text-white border-0">
                        <h4 class="text-120 mb-0">
                            <span class="text-90">{{$language->name}}</span>
                        </h4>
                    </div>
                    <div class="card-body">
{{--                        @if($errors->any())--}}
{{--                            {{dd($errors)}}--}}
{{--                        @endif--}}
                        @if($errors->any())
                            @if(array_key_exists('title.'.$language->locale, $errors->messages()))
                                @livewire('form.input-text', ['name' => 'title['.$language->locale.']', 'labelText' => __('multimedia::form.title'),'alignIcon' => 'append',
                                'image' => asset('assets_bpanel/flags/'.$language->locale.'.png'), 'required' => true, 'customErrorMessage' => $errors->messages()["title.$language->locale"][0]])
                            @else
                                @livewire('form.input-text', ['name' => 'title['.$language->locale.']', 'labelText' => __('multimedia::form.title'),'alignIcon' => 'append',
                                'image' => asset('assets_bpanel/flags/'.$language->locale.'.png'), 'required' => true])
                            @endif
                        @else
                            @livewire('form.input-text', ['name' => 'title['.$language->locale.']', 'labelText' => __('multimedia::form.title'),'alignIcon' => 'append',
                            'image' => asset('assets_bpanel/flags/'.$language->locale.'.png'), 'required' => true])
                        @endif

                        @if($errors->any())
                            @if(array_key_exists('description.'.$language->locale, $errors->messages()))
                                @livewire('form.textarea', ['name' => 'description['.$language->locale.']', 'labelText' => __('multimedia::form.description'), 'language' => $language->locale, 'alignIcon' => 'append',
                                'image' => asset('assets_bpanel/flags/'.$language->locale.'.png'), 'customErrorMessage' => $errors->messages()["description.$language->locale"][0]])
                            @else
                                @livewire('form.textarea', ['name' => 'description['.$language->locale.']', 'labelText' => __('multimedia::form.description'), 'language' => $language->locale, 'alignIcon' => 'append',
                                'image' => asset('assets_bpanel/flags/'.$language->locale.'.png')])
                            @endif
                        @else
                            @livewire('form.textarea', ['name' => 'description['.$language->locale.']', 'labelText' => __('multimedia::form.description'), 'language' => $language->locale, 'alignIcon' => 'append',
                            'image' => asset('assets_bpanel/flags/'.$language->locale.'.png')])
                        @endif



                        @if($errors->any())
                            @if(array_key_exists('alt.'.$language->locale, $errors->messages()))
                                @livewire('form.input-text', ['name' => 'alt['.$language->locale.']', 'labelText' => __('multimedia::form.alt'),'alignIcon' => 'append',
                                'image' => asset('assets_bpanel/flags/'.$language->locale.'.png'), 'customErrorMessage' => $errors->messages()["alt.$language->locale"][0]])
                            @else
                                @livewire('form.input-text', ['name' => 'alt['.$language->locale.']', 'labelText' => __('multimedia::form.alt'),'alignIcon' => 'append',
                                'image' => asset('assets_bpanel/flags/'.$language->locale.'.png')])
                            @endif
                        @else
                            @livewire('form.input-text', ['name' => 'alt['.$language->locale.']', 'labelText' => __('multimedia::form.alt'),'alignIcon' => 'append',
                            'image' => asset('assets_bpanel/flags/'.$language->locale.'.png')])
                        @endif
                    </div>

                @endforeach

            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form.save-button',['theme'=>'save'])
                @livewire('form.save-button',['theme'=>'reset'])
            </div>
        </form>
    </div>

@endsection

resources/views/edit.blade.php
@extends('bpanel.layouts.bpanel-app')

@section('styles')
    <link rel="stylesheet" href="{{ asset('assets_bpanel/css/multimedia.css') }}">
@endsection

@section('title', 'Editar archivo')

@section('content')
    <div class="card bcard multimedia-show">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('multimedia::form.edit') . ' ' . $multimedia->mediaModel->name}}</span>
            </h4>
        </div>
        <div class="card-body">
            <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('multimedia.update', $multimedia)}}" enctype="multipart/form-data">
                @csrf
                @method('PUT')

                @livewire('multimedia::multimedia-features', ['multimedia' => $multimedia, 'media' => $multimedia->mediaModel, 'imageExtensions' => $imageExtensions,
                'fileExtension' => $fileExtension, 'arrayImages' => $multimedia->mediaModel])
                @livewire('form.input-text', ['name' => 'name', 'labelText' => __('multimedia::form.name'), 'value' => $multimedia->mediaModel->first()->name])
                @livewire('form.input-text', ['name' => 'keywords', 'labelText' => __('multimedia::form.keywords'), 'value' => $multimedia->keywords])
                <br>

                @foreach($languages as $language)
                    <div class="card-header bgc-secondary-d1 text-white border-0">
                        <h4 class="text-120 mb-0">
                            <span class="text-90">{{$language->name}}</span>
                        </h4>
                    </div>
                    <div class="card-body">
                        @if($errors->any())
                            @if(array_key_exists('title.'.$language->locale, $errors->messages()))
                                @livewire('form.input-text', ['name' => 'title['.$language->locale.']', 'labelText' => __('multimedia::form.title'),'alignIcon' => 'append',
                                'image' => asset('assets_bpanel/flags/'.$language->locale.'.png'), 'required' => true, 'customErrorMessage' => $errors->messages()["title.$language->locale"][0],
                                'value' => $multimedia->getTranslation('title', $language->locale)])
                            @else
                                @livewire('form.input-text', ['name' => 'title['.$language->locale.']', 'labelText' => __('multimedia::form.title'),'alignIcon' => 'append',
                                'image' => asset('assets_bpanel/flags/'.$language->locale.'.png'), 'required' => true, 'value' => $multimedia->getTranslation('title', $language->locale)])
                            @endif
                        @else
                            @livewire('form.input-text', ['name' => 'title['.$language->locale.']', 'labelText' => __('multimedia::form.title'),'alignIcon' => 'append',
                            'image' => asset('assets_bpanel/flags/'.$language->locale.'.png'), 'required' => true, 'value' => $multimedia->getTranslation('title', $language->locale)])
                        @endif

                        @if($errors->any())
                            @if(array_key_exists('description.'.$language->locale, $errors->messages()))
                                @livewire('form.textarea', ['name' => 'description['.$language->locale.']', 'labelText' => __('multimedia::form.description'), 'language' => $language->locale, 'alignIcon' => 'append',
                                'image' => asset('assets_bpanel/flags/'.$language->locale.'.png'), 'customErrorMessage' => $errors->messages()["description.$language->locale"][0],
                                'value' => $multimedia->getTranslation('description', $language->locale)])
                            @else
                                @livewire('form.textarea', ['name' => 'description['.$language->locale.']', 'labelText' => __('multimedia::form.description'), 'language' => $language->locale, 'alignIcon' => 'append',
                                'image' => asset('assets_bpanel/flags/'.$language->locale.'.png'), 'value' => $multimedia->getTranslation('description', $language->locale)])
                            @endif
                        @else
                            @livewire('form.textarea', ['name' => 'description['.$language->locale.']', 'labelText' => __('multimedia::form.description'), 'language' => $language->locale, 'alignIcon' => 'append',
                            'image' => asset('assets_bpanel/flags/'.$language->locale.'.png'), 'value' => $multimedia->getTranslation('description', $language->locale)])
                        @endif



                        @if($errors->any())
                            @if(array_key_exists('alt.'.$language->locale, $errors->messages()))
                                @livewire('form.input-text', ['name' => 'alt['.$language->locale.']', 'labelText' => __('multimedia::form.alt'),'alignIcon' => 'append',
                                'image' => asset('assets_bpanel/flags/'.$language->locale.'.png'), 'customErrorMessage' => $errors->messages()["alt.$language->locale"][0], 'value' => $multimedia->getTranslation('alt', $language->locale)])
                            @else
                                @livewire('form.input-text', ['name' => 'alt['.$language->locale.']', 'labelText' => __('multimedia::form.alt'),'alignIcon' => 'append',
                                'image' => asset('assets_bpanel/flags/'.$language->locale.'.png'), 'value' => $multimedia->getTranslation('alt', $language->locale)])
                            @endif
                        @else
                            @livewire('form.input-text', ['name' => 'alt['.$language->locale.']', 'labelText' => __('multimedia::form.alt'),'alignIcon' => 'append',
                            'image' => asset('assets_bpanel/flags/'.$language->locale.'.png'), 'value' => $multimedia->getTranslation('alt', $language->locale)])
                        @endif
                    </div>

                @endforeach

                @livewire('utils::created-updated-info', ['model' => $multimedia])

                <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                    @livewire('form.save-button',['theme'=>'update'])
                    @livewire('form.save-button',['theme'=>'reset'])
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/index.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Multimedia')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('multimedia::form.list') }}</span>
            </h4>
        </div>
        <div class="card-body">
            @livewire('multimedia::multimedia-datatable')
        </div>
    </div>
@endsection

resources/views/livewire/media-library-images.blade.php
<div>
    <div class="text-right">
        <a class="btn btn-primary" wire:click="mediaLibraryTableModal">
            <i class="fa fa-plus-circle"></i> Biblioteca multimedia
        </a>
    </div>

    <div class="modal fade" id="mediaLibraryTableModal{{$type}}" tabindex="-1" aria-labelledby="mediaLibraryTableModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Biblioteca multimedia</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @livewire('multimedia::media-library-images-table', ['contentId' => $contentId, 'type' => $type])
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>


@push('scripts')
    <script>
        window.addEventListener("mediaLibraryTableModalOpen{{$type}}", function(){
            $("#mediaLibraryTableModal{{$type}}").modal("show");
        });
    </script>
@endpush

resources/views/livewire/media-library-table.blade.php
<td>
{{--    {{$row->attached}}--}}
    @if($type == "images")
        @livewire('utils::media-preview', ['media' => $row->getMedia('images')->first()], key('image-media-library-'.$row->id))
    @elseif($type == "documents")
        <div class="file-format-icon text-center">
            <img src="{{asset("assets_bpanel/icons/".\Bittacora\Utils\UtilsFacade::extractExtensionFromFilename($row->media->first()->file_name) .".png")}}" alt="">
        </div>
    @endif
</td>
@if($type == "documents")
    <td>
        {{$row->media->first()->file_name}}
    </td>
@endif
<td>
    @livewire('utils::model-translatable-attribute', ['model' => $row, 'attribute' => 'title'], key('image-media-library-attribute'.$row->id))
</td>
<td>
    @livewire('content-multimedia::toggle-content-multimedia-button', ['contentId' => $contentId, 'multimediaId' => $row->id, 'type' => $type], key('refreshToggleButton'.$row->id))
</td>

resources/views/livewire/multimedia-datatable.blade.php
<td>
    <div class="text-center">
        @livewire('utils::media-preview', ['media' => $row->mediaModel], key('multimedia-media-preview-'.$row->id))
    </div>
</td>
<td>
    <div class="text-center">
        {{$row->mediaModel->name}}
    </div>
</td>
<td>
    <div class="text-center">
        @livewire('utils::format-icon', ['mimeType' => \Bittacora\Utils\UtilsFacade::extractExtensionFromFilename($row->mediaModel->file_name)], key('multimedia-mime-'.$row->id))
    </div>
</td>
<td>
    <div class="text-center">
        {{\Bittacora\Utils\UtilsFacade::convertFromBytes($row->mediaModel->size)}}
    </div>
</td>
<td>
    <div class="text-center">
        @livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'multimedia', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el elemento?'], key('multimedia-buttons-'.$row->id))
    </div>
</td>

resources/views/livewire/multimedia-features.blade.php
<div class="container multimedia-features mb-4">
    <div class="row">
        <div class="col-sm-6">
            @if(in_array($fileExtension, $imageExtensions))
                <a href="{{$media->getUrl()}}" class="d-block text-center" data-fancybox="multimedia{{$media->id}}">
                    <img src="{{$media->getUrl('thumb-350')}}" alt="" class="w-50">
                </a>
            @else
                <div class="d-block text-center">
                    <img src="{{ asset("bpanel/icons/$fileExtension-512.png") }}" alt="" class="w-50">
                </div>
            @endif

        </div>
        <div class="col-sm-6">
            <table class="multimedia-table-features w-100">
                <thead>
                    <tr>
                        <th colspan="2">
                            {{ __('multimedia::form.features') }}
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ __('multimedia::form.name') }}:</td>
                        <td>{{$media->name}}</td>
                    </tr>
                    <tr>
                        <td>{{ __('multimedia::form.file_name') }}: </td>
                        <td>{{$media->file_name}}</td>
                    </tr>
                    <tr>
                        <td>{{ __('multimedia::form.mime_type') }}:</td>
                        <td>{{$media->mime_type}}</td>
                    </tr>
                    <tr>
                        <td>{{ __('multimedia::form.extension') }}: </td>
                        <td>{{\Bittacora\Utils\UtilsFacade::extractExtensionFromFilename($media->file_name)}}</td>
                    </tr>
                    <tr>
                        <td>{{ __('multimedia::datatable.size') }}:</td>
                        <td>{{\Bittacora\Utils\UtilsFacade::convertFromBytes($media->size)}}</td>
                    </tr>
                    <tr>
                        <td>{{ __('multimedia::form.keywords') }}:</td>
                        <td>{{$multimedia->keywords}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

resources/views/livewire/multimedia-images-library-table.blade.php
<x-livewire-tables::bs4.table.cell>
        @livewire('utils::media-preview', ['media' => $row->getMedia('images')->first()], key('image-media-library-'.$row->id))
</x-livewire-tables::bs4.table.cell>
<x-livewire-tables::bs4.table.cell>
    {{$row->getMedia('images')->first()->file_name}}
</x-livewire-tables::bs4.table.cell>
<x-livewire-tables::bs4.table.cell>
    <button class="addImage btn btn-primary" wire:click="$emit('addImageFromMediaLibraryTinyMce', {{$row->id}})">Añadir</button>
</x-livewire-tables::bs4.table.cell>

resources/views/livewire/multimedia-images-library.blade.php
<div id="prueba">
    <div class="modal fade" id="multimediaImagesLibrary" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" style="z-index:5000">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Biblioteca de imágenes</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @livewire('multimedia::multimedia-images-library-table')
                </div>
            </div>
        </div>
    </div>

    @push('scripts')
        <script>
            window.addEventListener("openMultimediaImagesLibraryModal", function(){
                $("#multimediaImagesLibrary").modal("show");
            });
            window.addEventListener("closeMultimediaImagesLibraryModal", function(){
                $("#multimediaImagesLibrary").modal("hide");
            });
        </script>
    @endpush
</div>

resources/views/multiupload.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Subida de ficheros múltiple')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('multimedia::form.multiupload') }}</span>
            </h4>
        </div>
        <div class="card-body">
                @livewire('form::input-file', ['name' => 'file[]', 'idField' => 'file', 'fieldWidth' => 12, 'required' => true, 'accept' => $allowedFormats, 'multiple' => true,
                'allowedFileExtensions' => $allowedExtensions, 'uploadUrl' => route('multimedia.multiuploadstore'), 'csrf' => true, 'showUpload' => false, 'showRemove' => true,
                'uploadAsync' => true, 'initialPreviewAsData' => true, 'overwriteInitial' => false])
        </div>
    </div>
@endsection

resources/views/partials/actions.blade.php
<div class="action-buttons">
    <a class="text-blue mx-2" href="{{route($scope.'.show',$id)}}">
        <i class="fa fa-search"></i>
    </a>
    <a class="text-success mx-2" href="{{route($scope.'.edit', $id)}}">
        <i class="fa fa-pencil"></i>
    </a>
    <form method="POST" class="d-inline mx-2"
          action="{{route($scope.'.destroy', $id)}}">
        {!!method_field('DELETE')!!}
        @csrf
        <button id="delete_button{{$id}}" type="submit" class="btn btn-primary-outline text-danger"
                @if($disabled) disabled @endif
                onclick="return confirm('¿Está seguro de querer borrar {{$message}}?')">
            <i class="fa fa-trash"></i>
        </button>
    </form>
</div>

resources/views/show.blade.php
@extends('bpanel.layouts.bpanel-app')

@section('styles')
    <link rel="stylesheet" href="{{ asset('assets_bpanel/css/multimedia.css') }}">
@endsection

@section('title', 'Mostrar datos de archivo')

@section('content')
    <div class="card bcard multimedia-show">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('multimedia::form.show') . ' ' . $multimedia->mediaModel()->first()->name}}</span>
            </h4>
        </div>
        <div class="card-body">
            @livewire('multimedia::multimedia-features', ['multimedia' => $multimedia, 'media' => $multimedia->mediaModel()->first(),
            'fileExtension' => $fileExtension, 'imageExtensions' => $imageExtensions])

            @foreach($languages as $key => $language)
                <div class="container multimedia-features">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="multimedia-table-features w-100">
                                <thead>
                                    <tr>
                                        <th colspan="2">
                                            <img src="{{ asset("assets_bpanel/flags/$language->locale.png") }}" alt=""> <span>{{ $language->name }}</span>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>
                                            {{ __('multimedia::form.title') }}
                                        </td>
                                        <td>
                                            {{ $multimedia->getTranslation('title', $language->locale) }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            {{ __('multimedia::form.description') }}
                                        </td>
                                        <td>
                                            {{ $multimedia->getTranslation('description', $language->locale) }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            {{ __('multimedia::form.alt') }}
                                        </td>
                                        <td>
                                            {{ $multimedia->getTranslation('alt', $language->locale) }}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            @endforeach

            @livewire('utils::created-updated-info', ['model' => $multimedia])
        </div>
    </div>

@endsection

@section('scripts')
    <script>
    </script>
@endsection